apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-2
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
    